"""CAT-Loss War Room - AI-powered catastrophic loss litigation research."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "BootstrapContext": "war_room.bootstrap",
    "bootstrap_runtime": "war_room.bootstrap",
    "discover_repo_root": "war_room.bootstrap",
    "cached_call": "war_room.cache_io",
    "EvidenceBoardClusterCard": "war_room.evidence_board",
    "EvidenceBoardItemPreview": "war_room.evidence_board",
    "EvidenceBoardReadModel": "war_room.evidence_board",
    "ExportHistoryEntry": "war_room.export_history",
    "ExportHistoryReadModel": "war_room.export_history",
    "IssueWorkspaceCaseCandidate": "war_room.issue_workspace",
    "IssueWorkspaceCard": "war_room.issue_workspace",
    "IssueWorkspaceCitationOutcome": "war_room.issue_workspace",
    "IssueWorkspaceReadModel": "war_room.issue_workspace",
    "MemoComposerClaimLink": "war_room.memo_composer",
    "MemoComposerReadModel": "war_room.memo_composer",
    "MemoComposerSectionCard": "war_room.memo_composer",
    "build_evidence_board": "war_room.evidence_board",
    "build_evidence_board_from_parts": "war_room.evidence_board",
    "build_export_history": "war_room.export_history",
    "build_export_history_from_parts": "war_room.export_history",
    "build_issue_workspace": "war_room.issue_workspace",
    "build_issue_workspace_from_parts": "war_room.issue_workspace",
    "build_memo_composer": "war_room.memo_composer",
    "build_memo_composer_from_parts": "war_room.memo_composer",
    "FeatureFlags": "war_room.settings",
    "load_settings": "war_room.settings",
    "RuntimeEnvironment": "war_room.settings",
    "score_url": "war_room.source_scoring",
    "CASE_INTAKE_REQUIRED_FIELDS": "war_room.query_plan",
    "CASE_INTAKE_OPTIONAL_FIELDS": "war_room.query_plan",
    "CASE_INTAKE_ALLOWED_FIELDS": "war_room.query_plan",
    "CaseIntake": "war_room.models",
    "ResearchPlan": "war_room.models",
    "RetrievalTask": "war_room.models",
    "Run": "war_room.models",
    "RunEvent": "war_room.models",
    "RunStage": "war_room.models",
    "RunTimelineReadModel": "war_room.models",
    "IntakeValidationError": "war_room.query_plan",
    "QuerySpec": "war_room.models",
    "build_research_plan": "war_room.query_plan",
    "query_plan_for_module": "war_room.query_plan",
    "generate_query_plan": "war_room.query_plan",
    "validate_case_intake_payload": "war_room.query_plan",
    "load_case_intake": "war_room.query_plan",
    "WeatherBrief": "war_room.models",
    "CarrierDocPack": "war_room.models",
    "CaseCandidate": "war_room.models",
    "CaseLawPack": "war_room.models",
    "CitationVerifyPack": "war_room.models",
    "EvidenceCluster": "war_room.models",
    "EvidenceItem": "war_room.models",
    "LegalIssue": "war_room.models",
    "ExportArtifact": "war_room.models",
    "MemoClaim": "war_room.models",
    "MemoSection": "war_room.models",
    "MemoRenderInput": "war_room.models",
    "ReviewEvent": "war_room.models",
    "RunAuditSnapshot": "war_room.models",
    "adapt_case_candidate": "war_room.models",
    "adapt_case_intake": "war_room.models",
    "adapt_memo_section": "war_room.models",
    "adapt_research_plan": "war_room.models",
    "adapt_retrieval_task": "war_room.models",
    "adapt_run": "war_room.models",
    "adapt_run_event": "war_room.models",
    "adapt_run_stage": "war_room.models",
    "adapt_run_timeline": "war_room.models",
    "adapt_query_plan": "war_room.models",
    "adapt_query_spec": "war_room.models",
    "adapt_run_audit_snapshot": "war_room.models",
    "adapt_weather_brief": "war_room.models",
    "adapt_carrier_doc_pack": "war_room.models",
    "adapt_caselaw_pack": "war_room.models",
    "adapt_evidence_board": "war_room.models",
    "adapt_export_history": "war_room.models",
    "adapt_issue_workspace": "war_room.models",
    "adapt_legal_issue": "war_room.models",
    "adapt_memo_composer": "war_room.models",
    "adapt_citation_verify_pack": "war_room.models",
    "case_candidate_to_payload": "war_room.models",
    "case_intake_to_payload": "war_room.models",
    "memo_section_to_payload": "war_room.models",
    "research_plan_to_payload": "war_room.models",
    "retrieval_task_to_payload": "war_room.models",
    "query_plan_to_payloads": "war_room.models",
    "query_spec_to_payload": "war_room.models",
    "run_audit_snapshot_from_memo_input": "war_room.models",
    "run_audit_snapshot_from_parts": "war_room.models",
    "run_audit_snapshot_to_payload": "war_room.models",
    "run_event_to_payload": "war_room.models",
    "run_stage_to_payload": "war_room.models",
    "run_timeline_to_payload": "war_room.models",
    "run_to_payload": "war_room.models",
    "weather_brief_to_payload": "war_room.models",
    "carrier_doc_pack_to_payload": "war_room.models",
    "caselaw_pack_to_payload": "war_room.models",
    "citation_verify_pack_to_payload": "war_room.models",
    "evidence_board_to_payload": "war_room.models",
    "export_history_to_payload": "war_room.models",
    "issue_workspace_to_payload": "war_room.models",
    "legal_issue_to_payload": "war_room.models",
    "memo_composer_to_payload": "war_room.models",
    "memo_render_input_from_parts": "war_room.models",
    "WarRoomSettings": "war_room.settings",
    "NotebookScenarioSelection": "war_room.notebook_runtime",
    "RetrievalContentsRequest": "war_room.retrieval",
    "RetrievalExecutionResult": "war_room.retrieval",
    "RetrievalProvider": "war_room.retrieval",
    "RetrievalSearchRequest": "war_room.retrieval",
    "execute_retrieval_search": "war_room.retrieval",
    "execute_retrieval_task": "war_room.retrieval",
    "fetch_retrieval_contents": "war_room.retrieval",
    "notebook_run_id_from_intake": "war_room.retrieval",
    "query_spec_to_retrieval_task": "war_room.retrieval",
    "ScenarioDefinition": "war_room.scenarios",
    "ScenarioAvailabilitySummary": "war_room.scenarios",
    "ScenarioValidationError": "war_room.scenarios",
    "default_scenario_id": "war_room.scenarios",
    "fixture_case_availability_summary": "war_room.scenarios",
    "list_scenarios": "war_room.scenarios",
    "load_scenario": "war_room.scenarios",
    "load_scenario_for_fixture_case": "war_room.scenarios",
    "scenario_availability_summary": "war_room.scenarios",
    "scenario_catalog_availability": "war_room.scenarios",
    "validate_scenario": "war_room.scenarios",
    "build_run_timeline": "war_room.workflow_summary",
    "build_run_timeline_read_model": "war_room.workflow_summary",
    "build_intake_from_scenario": "war_room.notebook_runtime",
    "build_notebook_citation_review": "war_room.notebook_runtime",
    "ensure_runtime_context": "war_room.notebook_runtime",
    "format_research_plan_preview": "war_room.workflow_summary",
    "format_run_timeline": "war_room.workflow_summary",
    "format_evidence_board": "war_room.evidence_board",
    "render_evidence_board_html": "war_room.evidence_board",
    "format_export_history": "war_room.export_history",
    "format_issue_workspace": "war_room.issue_workspace",
    "format_memo_composer": "war_room.memo_composer",
    "load_notebook_citation_fixture": "war_room.notebook_runtime",
    "load_selected_scenario": "war_room.notebook_runtime",
    "prepare_notebook_scenario": "war_room.notebook_runtime",
    "resolve_live_retrieval_enabled": "war_room.notebook_runtime",
    "scenario_warning_message": "war_room.notebook_runtime",
    "RUN_STATES": "war_room.orchestration",
    "STAGE_KEYS": "war_room.orchestration",
    "STAGE_STATUSES": "war_room.orchestration",
    "TERMINAL_RUN_STATES": "war_room.orchestration",
    "TERMINAL_STAGE_STATUSES": "war_room.orchestration",
    "RUN_STATE_TRANSITIONS": "war_room.orchestration",
    "STAGE_STATUS_TRANSITIONS": "war_room.orchestration",
    "REVIEWABLE_OUTPUT_STAGE_KEYS": "war_room.orchestration",
    "REVIEW_REQUIRED_STAGE_KEYS": "war_room.orchestration",
    "OrchestrationStateError": "war_room.orchestration",
    "UnknownRunStateError": "war_room.orchestration",
    "UnknownStageStateError": "war_room.orchestration",
    "InvalidStateTransitionError": "war_room.orchestration",
    "StageStateSnapshot": "war_room.orchestration",
    "derive_run_status_from_stages": "war_room.orchestration",
    "ensure_run_status": "war_room.orchestration",
    "ensure_stage_key": "war_room.orchestration",
    "ensure_stage_status": "war_room.orchestration",
    "is_terminal_run_status": "war_room.orchestration",
    "is_terminal_stage_status": "war_room.orchestration",
    "normalize_stage_state": "war_room.orchestration",
    "normalize_stage_states": "war_room.orchestration",
    "run_requires_review": "war_room.orchestration",
    "validate_run_transition": "war_room.orchestration",
    "validate_stage_transition": "war_room.orchestration",
    "DEFAULT_START_STAGE_KEYS": "war_room.orchestration_api_contracts",
    "GetRunStatusResponse": "war_room.orchestration_api_contracts",
    "OrchestrationErrorResponse": "war_room.orchestration_api_contracts",
    "OrchestrationFailurePayload": "war_room.orchestration_api_contracts",
    "OrchestrationRunStatusPayload": "war_room.orchestration_api_contracts",
    "OrchestrationStagePayload": "war_room.orchestration_api_contracts",
    "OrchestrationTimelinePayload": "war_room.orchestration_api_contracts",
    "OrchestrationUsableOutputPayload": "war_room.orchestration_api_contracts",
    "StartRunRequest": "war_room.orchestration_api_contracts",
    "StartRunResponse": "war_room.orchestration_api_contracts",
    "adapt_get_run_status_response": "war_room.orchestration_api_contracts",
    "adapt_orchestration_error_response": "war_room.orchestration_api_contracts",
    "adapt_orchestration_stage": "war_room.orchestration_api_contracts",
    "adapt_start_run_request": "war_room.orchestration_api_contracts",
    "adapt_start_run_response": "war_room.orchestration_api_contracts",
    "get_run_status_response_to_payload": "war_room.orchestration_api_contracts",
    "orchestration_error_response_to_payload": "war_room.orchestration_api_contracts",
    "run_payload_for_api": "war_room.orchestration_api_contracts",
    "run_status_payload_from_run": "war_room.orchestration_api_contracts",
    "start_run_request_to_payload": "war_room.orchestration_api_contracts",
    "start_run_response_to_payload": "war_room.orchestration_api_contracts",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str):
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(_EXPORTS[name])
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
